/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_mobile_analytics_app_id": "ec4aae0f89b34f56b9ffdc5cb32f2a75",
    "aws_mobile_analytics_app_region": "us-east-1"
};


export default awsmobile;
