/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:692ef2d2-b796-4386-b976-6a4120def2a5",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_DPYh1WiDO",
    "aws_user_pools_web_client_id": "4v4hbsrvlftvhmdhjmspjvkuc3",
    "oauth": {
        "domain": "chaos-dev.auth.us-east-1.amazoncognito.com",
        "scope": [
            "phone",
            "email",
            "openid",
            "profile",
            "aws.cognito.signin.user.admin"
        ],
        "redirectSignIn": "https://localhost:3000/",
        "redirectSignOut": "http://localhost:3000/signout/",
        "responseType": "code"
    },
    "federationTarget": "COGNITO_USER_POOLS",
    "aws_mobile_analytics_app_id": "642cfb0be73d4b09a2e29462e604efbb",
    "aws_mobile_analytics_app_region": "us-east-1"
};


export default awsmobile;
